### ISSUE TITLE
无法正确上传包含空格的文件

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/WorldShare#110]
比如`1 - copy.png`在上传后会变成`1+-+copy.png`， 导致用户的作品分享后， 无法正确显示

**Comment by LiXizhi** [comment]
[testskin.zip](https://github.com/tatfook/WorldShare/files/2729649/testskin.zip)
测试世界

**Comment by onedou** [comment]
Issue moved to [tatfook/keepwork #3576](https://github.com/tatfook/keepwork/issues/3576) via [**ZenHub**](https://www.zenhub.com/)
