### ISSUE TITLE
首次分享世界成功后，还是显示没有分享

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/WorldShare#118]
![image.png](https://images.zenhubusercontent.com/5925484051aa2c30577f488d/ab5a55cd-2cf7-4c82-ae1c-6daf9e4681fc)

分享成功后， 这里还是显示没有分享， 也无法查看分享链接。

**Comment by onedou** [comment]
可能没有获取到projectId

**Comment by onedou** [comment]
Issue moved to [tatfook/paracraft #114](https://github.com/tatfook/paracraft/issues/114) via [**ZenHub**](https://www.zenhub.com/)
