### ISSUE TITLE
上传数据源完成后，更新服务器列表失败后，无法再次上传世界，列表无projectId导致

### ISSUE THREAD

**Issue by onedou** [tatfook/WorldShare#43]

**Comment by Sandu1213** [comment]
在ver:0.7.341上验证通过
![image](https://user-images.githubusercontent.com/21214285/33306554-00a35514-d44e-11e7-8241-b6b2ca40d9fb.png)

**Comment by Sandu1213** [comment]
在V0.7.343上上传失败，待排查

**Comment by onedou** [comment]
删除方法变量错误导致，非projectid

**Comment by Sandu1213** [comment]
验证通过
