### ISSUE TITLE
截图后，自动增加版本号

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/WorldShare#45]
![image](https://user-images.githubusercontent.com/94537/26862124-6992e49c-4b7b-11e7-96b1-a6e12521e842.png)

1 在分享UI增加打开所在目录的功能
2. 分享UI点击截图后，如果版本号和服务器一样，需要自动增加版本号

![image](https://user-images.githubusercontent.com/94537/26862175-af577470-4b7b-11e7-8a4f-8c611aa28031.png)

**Comment by Sandu1213** [comment]
在 ver: 0.7.340验证通过
