### ISSUE TITLE
ZIP读取文件内容出错

### ISSUE THREAD

**Issue by onedou** [tatfook/WorldShare#47]
读ZIP内容是为数字时，内容出错。
测试代码：
https://github.com/LiXizhi/NPLRuntime/wiki/FilesAndIO#search-and-read-file-in-zip-file

出错文件 revision.xml

测试ZIP包
[archive.zip](https://github.com/tatfook/WorldShare/files/1059746/archive.zip)

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/26909172-a969135a-4c31-11e7-927a-68edfe3d3be4.png)

**Comment by LiXizhi** [comment]
should already be fixed in recent release
