### ISSUE TITLE
上传限制改成25兆。列出容量较大的文件。提示建议用户使用MP3 ogg格式的声音，少用fbx格式

### ISSUE THREAD

**Issue by onedou** [tatfook/WorldShare#64]

**Comment by LiXizhi** [comment]
这个改好，告诉我下。 少用FBX,STL等

**Comment by Sandu1213** [comment]
目前改为会存在提醒，但不会列出较大文件的信息，需要用户自己去筛查处理。
---实现上缺少判断VIP用户，使用的VIP账号进行上传，还是限制25M,请调整 (**用户名：dukes**)
![image](https://user-images.githubusercontent.com/21214285/33305098-698c58de-d447-11e7-9ef8-c4b698571f60.png)
![image](https://user-images.githubusercontent.com/21214285/33305207-e7b7bdd4-d447-11e7-938c-44f4afa8651c.png)

**Comment by onedou** [comment]
现在列出较大的文件在哪里显示？
开通VIP后就没有上传限制了吗？单个文件最大200M

**Comment by LiXizhi** [comment]
世界上传 我们客户端限制不允许太大。 VIP也只能50. 和后台实际的不相关

**Comment by onedou** [comment]
VIP的超限提示暂时为：您最多可以上传50MB的内容

**Comment by Sandu1213** [comment]
test环境验证通过
