### ISSUE TITLE
自动登录时，列表载入出错

### ISSUE THREAD

**Issue by onedou** [tatfook/WorldShare#65]

**Comment by LiXizhi** [comment]
目前有这个问题么？ 紧急么？

**Comment by onedou** [comment]
偶尔会出现，在找原因，不自动登录就没事

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/30194088-aadd7ac4-9483-11e7-86c1-3f50ed32b861.png)

**Comment by LiXizhi** [comment]
Fixed？

**Comment by onedou** [comment]
今天修复@LiXiZhi
