### ISSUE TITLE
上传大文件失败，错误代码417

### ISSUE THREAD

**Issue by onedou** [tatfook/WorldShare#66]
上传大文件失败

<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\
<HTML><HEAD>\
<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=utf-8\"> \
<TITLE>错误：您所请求的网址（URL）无法获取</TITLE>\
<STYLE type=\"text/css\"></STYLE>\
</HEAD><BODY>\
<H1>错误</H1>\
<H2>您所请求的网址（URL）无法获取</H2>\
<HR noshade size=\"1px\">\
<P>\
当尝试进行以下请求时：\
<PRE>\
POST /api/v4/projects/9298/repository/files/Deptford+Goth%2DFeel+Real%2Emp3 HTTP/1.1\
Host: git.keepwork.com\13\
Accept: */*\13\
User-Agent: npl\13\
Content-Type: application/json\13\
PRIVATE-TOKEN: iTEu22Do2hnYKgvVq6Qj\13\
Content-Length: 17528762\13\
Expect: 100-continue\13\
X-Forwarded-For: 223.73.229.200\13\
Cdn-Src-Ip: 223.73.229.200\13\
X-Client-Switch-Rtt: 41871\13\
X-Http-Protocol: http\13\
\
</PRE>\
<P>\
发生了下列的错误：\
<UL>\
<LI>\
<STRONG>\
Invalid Request\
<BR>\
无效的请求\
</STRONG>\
</UL>\
\
<P>\
Some aspect of the HTTP Request is invalid.  Possible problems:\
<BR>\
HTTP 请求的某些方面是无效的。可能是下列问题：\
<UL>\
<LI>Missing or unknown request method\
<BR>缺少请求方式或未知的请求方式\
<LI>Missing URL\
<BR>缺少网址\
<LI>Missing HTTP Identifier (HTTP/1.0)\
<BR>缺少 HTTP 标识（HTTP/1.0）\
<LI>Request is too large\
<BR>请求命令过长\
<LI>Content-Length missing for POST or PUT requests\
<BR>POST 或 PUT 请求缺少内容长度\
<LI>Illegal character in hostname; underscores are not allowed\
<BR>主机名称中包含不合法的字符；下划线是不允许的。\
<LI>Requested range is not satisfiable\
<BR>请求的Range范围不合法。\
</UL>\
</P>\
<P>本缓存服务器管理员：<A HREF=\"mailto:wssupport@chinanetcenter.com\">wssupport@chinanetcenter.com</A>. \
<P>Via:PSgddgydvw23:9 (Cdn Cache Server V2.0)</P>\
\
<BR clear=\"all\">\
<HR noshade size=\"1px\">\
<ADDRESS>\
Generated Mon, 18 Sep 2017 13:00:31 GMT by cache.51cdn.com (Cdn Cache Server V2.0)\
</ADDRESS>\
</BODY></HTML>\

**Comment by leopoldchen** [comment]
如果是bug issue，最好先让QA帮忙做一下重现。

**Comment by onedou** [comment]
是服务器请求数据长度限制，我这里用判断base64的文件长度即可，这个之后修复

**Comment by onedou** [comment]
现在上传最大值是300m，因为有一些其他的数据，所以上传的大小限制到250m。若上传失败417，提示文件最大为250m

**Comment by onedou** [comment]
服务器上传上限已调至200m 此情况应该不会出现，请测试

**Comment by Sandu1213** [comment]
VIP用户最多可以上传50M，非VIP用户最多可以上传25M，超过限制会给出提示，需要用户手动进行清理后才可以再上传。
在test环境验证通过。
