### ISSUE TITLE
英文本地化

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/WorldShare#69]
参考paracraft的做法。 加入`L""`

**Comment by Sandu1213** [comment]
Share相关的英文版本验证通过，但备份会出现中文的情况，请调整，谢谢。
![image](https://user-images.githubusercontent.com/21214285/32713744-a022d1f2-c885-11e7-85bf-2f188bcfed5f.png)

**Comment by Sandu1213** [comment]
已经验证完成，图中问题xizhi晚些会处理。

**Comment by Sandu1213** [comment]
问题依然存在，请调整。
![image](https://user-images.githubusercontent.com/21214285/33107187-0de0b8f2-cf71-11e7-8aca-2330b51edeb9.png)
![default](https://user-images.githubusercontent.com/21214285/33107460-595f5ca6-cf72-11e7-91d6-e507df184591.png)
![2](https://user-images.githubusercontent.com/21214285/33107462-599d8788-cf72-11e7-9224-f53cfad0f731.png)
![3](https://user-images.githubusercontent.com/21214285/33107463-59da3368-cf72-11e7-8a92-6513ed5edc5e.png)
