### ISSUE TITLE
命令行进入世界，无法登陆分享

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/WorldShare#70]
`start.bat` like below
```
start ParaEngineClient.exe single="false" httpdebug="true" debug="main" mc="true" world="worlds/DesignHouse/MultiplayerTest"
```

ESC，点击分享， 登陆后无反应。是缺少了某个初始化么？

**Comment by onedou** [comment]
https://github.com/tatfook/WorldShare/commit/b32f8484d6037297903914f76fd735f286031a9a

**Comment by Sandu1213** [comment]
修改bat，指向对应的世界后，进行登陆分享，可以分享成功。test环境验证通过。
