### ISSUE TITLE
使用敏感词创建世界时提示无法创建

### ISSUE THREAD

**Issue by onedou** [tatfook/WorldShare#72]
使用敏感词创建世界时没有提示使用了敏感词，而卡在sha列表

**Comment by Sandu1213** [comment]
V0.7.346 版本验证不过，还是可以创建含敏感词的世界

![image](https://user-images.githubusercontent.com/21214285/34924202-f5e85bd8-f9dc-11e7-9160-ff819fb2b5eb.png)

**Comment by Sandu1213** [comment]
判断不是太合理，请与keepwork的保存一致。
![image](https://user-images.githubusercontent.com/21214285/34929407-a4160ea0-f9fe-11e7-9908-0ea61cc1fe81.png)

**Comment by onedou** [comment]
release上的敏感词好像不够多，请在keepwork.com测试

**Comment by Sandu1213** [comment]
keepwork环境也是存在问题，请排查

**Comment by onedou** [comment]
现在是在创建的时候限制，不是在上传的时候限制
