### ISSUE TITLE
分享世界时自动填充项目预览图

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/WorldShare#91]
![image](https://user-images.githubusercontent.com/94537/48618879-9a402100-e9d5-11e8-8655-1a262072d1cb.png)

分享世界时自动填充项目预览图 （如果之前不存在的化）

**Comment by onedou** [comment]
Issue moved to [tatfook/keepwork #3001](https://github.com/tatfook/keepwork/issues/3001) via [**ZenHub**](https://www.zenhub.com/)
