### ISSUE TITLE
加载世界信息时按需加载

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/WorldShare#93]
当我有非常多的个人世界时（30-100个左右），LoadWorld页面要卡死5-10秒才能加载出来。 
能否先只读列表，只有当下拉显示时，才refresh和读取tag.xml. 尤其是针对zip文件。

![image](https://user-images.githubusercontent.com/94537/48749043-0b245900-ecb4-11e8-810b-991c8f15ee28.png)

**Comment by onedou** [comment]
Issue moved to [tatfook/keepwork #3039](https://github.com/tatfook/keepwork/issues/3039) via [**ZenHub**](https://www.zenhub.com/)
