### ISSUE TITLE
输入ProjectID进入世界，可否自动检测更新

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/WorldShare#97]
输入ProjectID进入世界，可否自动检测更新

我们API的返回值中是否能看到上传提交的commit id? 如果可以，最好提示用户

“XXX世界更新了，你的本地版本为旧版本，是否重新下载？”

**Comment by onedou** [comment]
Issue moved to [tatfook/keepwork #3199](https://github.com/tatfook/keepwork/issues/3199) via [**ZenHub**](https://www.zenhub.com/)
